export default {
  activeList: [
    {
      "addDate": "2019-10-09 14:33:58",
      "commentContent": "什么情况",
      "commonAccount": 13,
      "fabulousAccount": 4,
      "fansCurrencyName": "",
      "hasGroup": false,
      "id": 106433,
      "imglist": [],
      "isfans": false,
      "ismine": false,
      "isvip": 0,
      "kolid": 147435,
      "kolname": "苹果滴",
      "kolpic": "",
      "myFabulousAccount": 0,
      "myTreadAccount": 0,
      "operationLevelPic": "http://app.tokenmaster.io/file/operationlevel/qingtong.png",
      "operationLevelTitle": "青铜",
      "treadAccount": 0,
      "userLevelTitle": "04"
    },
    {
      "addDate": "2019-10-09 14:33:58",
      "commentContent": "什么情况",
      "commonAccount": 13,
      "fabulousAccount": 4,
      "fansCurrencyName": "",
      "hasGroup": false,
      "id": 106433,
      "imglist": [],
      "isfans": false,
      "ismine": false,
      "isvip": 0,
      "kolid": 147435,
      "kolname": "苹果滴",
      "kolpic": "",
      "myFabulousAccount": 0,
      "myTreadAccount": 0,
      "operationLevelPic": "http://app.tokenmaster.io/file/operationlevel/qingtong.png",
      "operationLevelTitle": "青铜",
      "treadAccount": 0,
      "userLevelTitle": "04"
    },
    {
      "addDate": "2019-10-09 14:33:58",
      "commentContent": "什么情况",
      "commonAccount": 13,
      "fabulousAccount": 4,
      "fansCurrencyName": "",
      "hasGroup": false,
      "id": 106433,
      "imglist": [],
      "isfans": false,
      "ismine": false,
      "isvip": 0,
      "kolid": 147435,
      "kolname": "苹果滴",
      "kolpic": "",
      "myFabulousAccount": 0,
      "myTreadAccount": 0,
      "operationLevelPic": "http://app.tokenmaster.io/file/operationlevel/qingtong.png",
      "operationLevelTitle": "青铜",
      "treadAccount": 0,
      "userLevelTitle": "04"
    },
    {
      "addDate": "2019-10-09 14:33:58",
      "commentContent": "什么情况",
      "commonAccount": 13,
      "fabulousAccount": 4,
      "fansCurrencyName": "",
      "hasGroup": false,
      "id": 106433,
      "imglist": [],
      "isfans": false,
      "ismine": false,
      "isvip": 0,
      "kolid": 147435,
      "kolname": "苹果滴",
      "kolpic": "",
      "myFabulousAccount": 0,
      "myTreadAccount": 0,
      "operationLevelPic": "http://app.tokenmaster.io/file/operationlevel/qingtong.png",
      "operationLevelTitle": "青铜",
      "treadAccount": 0,
      "userLevelTitle": "04"
    },
    {
      "addDate": "2019-10-09 14:33:58",
      "commentContent": "什么情况",
      "commonAccount": 13,
      "fabulousAccount": 4,
      "fansCurrencyName": "",
      "hasGroup": false,
      "id": 106433,
      "imglist": [],
      "isfans": false,
      "ismine": false,
      "isvip": 0,
      "kolid": 147435,
      "kolname": "苹果滴",
      "kolpic": "",
      "myFabulousAccount": 0,
      "myTreadAccount": 0,
      "operationLevelPic": "http://app.tokenmaster.io/file/operationlevel/qingtong.png",
      "operationLevelTitle": "青铜",
      "treadAccount": 0,
      "userLevelTitle": "04"
    }
  ]
}